-- database/schema.sql
-- Run this in your Supabase SQL Editor

-- Create beers table
CREATE TABLE beers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  style TEXT NOT NULL,
  abv DECIMAL(3,1) NOT NULL,
  description TEXT NOT NULL,
  season TEXT NOT NULL,
  hops TEXT NOT NULL,
  malts TEXT NOT NULL,
  extras TEXT,
  imageUrl TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create contact submissions table
CREATE TABLE contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  beer_type TEXT NOT NULL,
  quantity TEXT NOT NULL,
  occasion TEXT,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create recipes table (optional enhancement)
CREATE TABLE recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('Easy', 'Intermediate', 'Advanced')),
  ingredients JSONB NOT NULL,
  instructions JSONB NOT NULL,
  pairing_notes TEXT NOT NULL,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE beers ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;

-- Create policies for anonymous access
CREATE POLICY "Allow anonymous read access to beers" 
ON beers FOR SELECT 
TO anon
USING (true);

CREATE POLICY "Allow anonymous read access to recipes" 
ON recipes FOR SELECT 
TO anon
USING (true);

CREATE POLICY "Allow anonymous insert to contact submissions" 
ON contact_submissions FOR INSERT 
TO anon
WITH CHECK (true);

-- Insert sample beer data
INSERT INTO beers (name, style, abv, description, season, hops, malts, extras, imageUrl)
VALUES 
  ('Langer''s Lager', 'Japanese Lager', 5.2, 'A refreshing rice lager that goes down just a little too smooth', 'summer', 'german', '2row, light crystal', 'rice', '3beertbl.jpg'),
  ('Sour Kicks', 'Sour', 5.5, 'A sour with some sour gummies', 'spring', 'chinook, rocket, and special', 'pale ale, flaked oats', 'haribo sour kicks', '3beertbl.jpg'),
  ('Blonde Muse', 'Belgian Blonde', 6.5, 'A subtle yet robust beer with notes of lemon, cloves and ginger. Inspiring you to do a little bit more.', 'spring', 'hersbrucker, chinook', 'pilsner, maris otter, munich, victory', 'cloves, lemon rind, ginger', '3beertbl.jpg');

-- Insert sample recipe data
INSERT INTO recipes (title, description, difficulty, ingredients, instructions, pairing_notes, image_url)
VALUES 
  (
    'Beer-Battered Fish',
    'Crispy fish fillets coated in our Classic Lager batter, creating a light and airy texture.',
    'Easy',
    '["1 1/2 cups all-purpose flour", "1 tsp baking powder", "1 tsp salt", "1/2 tsp ground black pepper", "1 cup Langer''s Classic Lager", "1 lb white fish fillets (cod or haddock)", "Vegetable oil for frying"]',
    '["In a large bowl, combine flour, baking powder, salt, and pepper.", "Gradually whisk in the Langer''s Classic Lager until smooth. Let rest for 15 minutes.", "Heat oil in a deep fryer or large pot to 375°F (190°C).", "Pat fish fillets dry and dip into the batter, allowing excess to drip off.", "Carefully lower into hot oil and fry until golden brown, about 3-4 minutes.", "Remove and drain on paper towels. Serve immediately with lemon wedges."]',
    'Pairs wonderfully with our Classic Lager or Amber Ale for a perfect flavor combination.',
    NULL
  ),
  (
    'Beer Bread',
    'Easy homemade bread with a hint of malty sweetness from our Amber Ale.',
    'Easy',
    '["3 cups self-rising flour", "1/4 cup sugar", "12 oz Langer''s Amber Ale", "2 tbsp melted butter"]',
    '["Preheat oven to 375°F (190°C) and grease a 9x5 inch loaf pan.", "In a large bowl, mix flour and sugar.", "Slowly pour in Langer''s Amber Ale and stir until just combined.", "Transfer the batter to the prepared loaf pan.", "Pour melted butter over the top of the batter.", "Bake for 45-55 minutes until the top is golden brown and a toothpick inserted in the center comes out clean.", "Let cool for 10 minutes before removing from the pan."]',
    'Serve warm with butter alongside a cold glass of Amber Ale for a rustic treat.',
    NULL
  );
